### ISSUE TITLE
Clarify the game mechanics

### ISSUE THREAD

**Issue by romac** [reminisceme/backend#22]
1. Alice invites Bob to play with her.
2. Bob receives a join request, that he can either decline or accept.
3. If Bob declines, nothing happens for him, but Alice is notified that Bob declined the invitation.
4. If Bob accepts, then a new game is started, which appears in each player's dashboard under "Current Games".
5. One of the two players, chosen at random, plays first. Let's say that's Alice.
6. Alice can click on any tile she likes, and she's then asked 3 questions about either her or Bob in case she clicked on the central tile.
7. Alice selects the tile titled "Lost in time", and correctly answers 2 out of 3 questions.
8. The tile is now marked as following (given that A is red)

![2/3](https://cloud.githubusercontent.com/assets/106849/4135605/9ce29fc8-3377-11e4-9d1f-96f6f4404208.png)

9. It's now Bob's turn. **Can Bob select the same tile that Alice just selected, since that tile isn't completely answered yet? If yes, how should the tile be display if say Bob got 1 question right, while Alice got 2 of them right?**
10. Let's say Bob chooses another tile, answers some questions, etc.
11. It's Alice's turn again. **Can she now re-select the tile she selected at step 7, since there's still one question she got wrong. If yes, how many questions will she be asked? 1 or 3?**
12. And so on…
13. The game ends when one of them fully *controls* (see below) 3 tiles on the same row, column or diagonal.

![3/3](http://cl.ly/image/3C360I0L0b3Y/Screen%20Shot%202014-09-03%20at%2016.43.31.png)

**Comment by pirroh** [comment]
I remember we clarified this in person, but for the sake of documenting correctly this issue:
* if a tile is not permanently conquered (i.e., 3 out of 3 correct answers) the players can keep on playing on it
* playing on a tile that has been already *temporarily* conquered by Player1 (i.e., 1 or 2 out of 3 correct answers) leads to a permanently conquered tile for Player2 if score(Player2) > score(Player1), or  to a permanently conquered tile for Player1 if score(Player1) > score(Player2)
* we'll figure out how to break the ties later on (as it is an opportunity to embed different types of questions with different research goals)
