### ISSUE TITLE
NewJoinRequest view expects an e-mail address rather than the opponent id

### ISSUE THREAD

**Issue by romac** [reminisceme/backend#38]
When we select a user to start a game in the web app, it currently sends that user's Facebook id to the backend (as documented on the wiki), whereas the backend currently expects an e-mail address.

Is there any advantage to asking for the e-mail address rather than the Facebook id?

I'm asking as I'm not sure there's a way for the web app to access a friend's e-mail address.

**Comment by JRappaz** [comment]
Mhh the query to retrieve the user will be more complex but I will try. Keep you informed.
