### ISSUE TITLE
What's settings.BACKEND_URL supposedly pointed at?

### ISSUE THREAD

**Issue by romac** [reminisceme/backend#41]
It's currently equal to `http://localhost:9900` but there's nothing running at that address on the droplet.

**Comment by JRappaz** [comment]
The game creator from @Aranir should respond to:

`http://localhost:9900/gameboard?user_id=1234556`
`http://localhost:9900/fetchData?user_id=1234556&access_token=83921039210831290`

He worked on it this afternoon so maybe it is not up at the moment

**Comment by romac** [comment]
Okay, thanks :)

**Comment by pirroh** [comment]
Nitpicking here (I know, I know...) but before we get crazy with naming, I think this should not be called BACKEND_URL, but rather GAMECREATOR_URL -- i.e., the BACKEND_URL is the Django app itself :)

**Comment by romac** [comment]
Opened a new issue for the renaming: #45.
